### ISSUE TITLE
Missing extension byte

### ISSUE THREAD

**Issue by adrianvintu** [sur950/any_link_preview#77]
I understand this is a UTF decoding issue, but why does it work for you and not for me?

I am using the example code 
```
Metadata? _metadata = await AnyLinkPreview.getMetadata(
  link: "https://google.com/",
  cache: Duration(days: 7),  
);
```

I get

```
I/flutter (19786): FormatException: Missing extension byte (at offset 12090)
I/flutter (19786): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1741:7)
I/flutter (19786): #1      Utf8Decoder.convert (dart:convert/utf.dart:349:37)
I/flutter (19786): #2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
I/flutter (19786): #3      LinkAnalyzer.responseToDocument (package:any_link_preview/src/helpers/link_analyzer.dart:154:29)
I/flutter (19786): #4      LinkAnalyzer.getInfo (package:any_link_preview/src/helpers/link_analyzer.dart:128:24)
I/flutter (19786): <asynchronous suspension>
I/flutter (19786): #5      AnyLinkPreview._getMetadata (package:any_link_preview/src/helpers/link_preview.dart:200:18)
I/flutter (19786): <asynchronous suspension>
I/flutter (19786): #6      metadataService (package:stop_anxiety/screens/message/chat/metadata_service_provider.dart:11:27)
I/flutter (19786): <asynchronous suspension>
I/flutter (19786): #7      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348:9)
I/flutter (19786): <asynchronous suspension>
```

The response is

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ro"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){var _g={kEI:'aF27ZsLgMq-P9u8Ppp-gkA8',kEXPI:'0,793344,1711180,1195804,1053,8,89,541439,2891,11754,77401,163859,2,39761,6700,41945,84374,8155,23351,22435,9779,12415,50243,73178,3030,15816,1804,14360,12048,20674,1632,29279,5239759,996,128,5991306,849,2840330,1,33,72,25,27980825,16673,43886,3,318,4,1281,3,2124363,23029351,12799,14986,38114,12358,51849,5796,12952,2213,8181,150,28546,34987,9,7408,6753,156,2483,4401,9103,1006,6731,7041,2097,740,2,1,3856,328,1544,1673,5,3004,4616,11,2959,5,12082,409,519,3765,3624,5634,686,6674,1122,3,417,1354,1244,2694,4480,1346,3884,852,217,2020,3548,682,664,5842,339,7467,55,1490,722,2,9,3997,3,2709,151,1707,294,3207,1343,2376,567,919,316,481,181,307,222,1858,2,2703,150,14,1832,1,6,197,2084,69,5,795,22,2449,4,248,1370,454,3004,1748,1620,77,1448,422,462,2097,565,98,2392,245,882,1555,766,1363,413,39,2917,189,178,32,2,351,712,59,440,116,10,499,164,274,122,599,755,677,534,9,576,1131,597,7750,1029,1344,652,204,370,242,652,2,1127,3,126,2,373,7,32,1070,162,917,379,270,7,4,148,3,2,179,207,332,20,782,86,248,1489,192,3,14,241,661,258,463,42,230,40,463,3,579,85,19,24,1091,414,20,354,26,33,148,71,1025,821,701,152,82,40,73,1105,154,969,106,515,224,76,1,8,1,1,4,1,4,920,163,429,225,543,891,230,36,353,538,264,71,980,21137651,365636,3,10196,4,4275,3,7053,1112,47,616,994735',kBL:'IANt',kOPI:89978449};(function(){var a;((a=window.google)==null?0:a.stvsc)?google.kEI=_g.kEI:window.google=_g;}).call(this);})();(function(){google.sn='webhp';google.kHL='ro';})();(function(){
var h=this||self;function l(){return window.google!==void 0&&window.google.kOPI!==void 0&&window.google.kOPI!==0?window.google.kOPI:null};var m,n=[];function p(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||m}function q(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b}function r(a){/^http:/i.test(a)&&window.location.protocol==="https:"&&(google.ml&&google.ml(Error("a"),!1,{src:a,glmm:1}),a="");return a}
function t(a,b,c,d,k){var e="";b.search("&ei=")===-1&&(e="&ei="+p(d),b.search("&lei=")===-1&&(d=q(d))&&(e+="&lei="+d));d="";var g=b.search("&cshid=")===-1&&a!=="slh",f=[];f.push(["zx",Date.now().toString()]);h._cshid&&g&&f.push(["cshid",h._cshid]);c=c();c!=null&&f.push(["opi",c.toString()]);for(c=0;c<f.length;c++){if(c===0||c>0)d+="&";d+=f[c][0]+"="+f[c][1]}return"/"+(k||"gen_204")+"?atyp=i&ct="+String(a)+"&cad="+(b+e+d)};m=google.kEI;google.getEI=p;google.getLEI=q;google.ml=function(){return null};google.log=function(a,b,c,d,k,e){e=e===void 0?l:e;c||(c=t(a,b,e,d,k));if(c=r(c)){a=new Image;var g=n.length;n[g]=a;a.onerror=a.onload=a.onabort=function(){delete n[g]};a.src=c}};google.logUrl=function(a,b){b=b===void 0?l:b;return t("",a,b)};}).call(this);(function(){google.y={};google.sy=[];var d;(d=google).x||(d.x=function(a,b){if(a)var c=a.id;else{do c=Math.random();while(google.y[c])}google.y[c]=[a,b];return!1});var e;(e=google).sx||(e.sx=function(a){google.sy.push(a)});google.lm=[];var f;(f=google).plm||(f.plm=function(a){google.lm.push.apply(google.lm,a)});google.lq=[];var g;(g=google).load||(g.load=function(a,b,c){google.lq.push([[a],b,c])});var h;(h=google).loadAll||(h.loadAll=function(a,b){google.lq.push([a,b])});google.bx=!1;var k;(k=google).lx||(k.lx=function(){});var l=[],m;(m=google).fce||(m.fce=function(a,b,c,n){l.push([a,b,c,n])});google.qce=l;}).call(this);google.f={};(function(){
document.documentElement.addEventListener("submit",function(b){var a;if(a=b.target){var c=a.getAttribute("data-submitfalse");a=c==="1"||c==="q"&&!a.elements.q.value?!0:!1}else a=!1;a&&(b.preventDefault(),b.stopPropagation())},!0);document.documentElement.addEventListener("click",function(b){var a;a:{for(a=b.target;a&&a!==document.documentElement;a=a.parentElement)if(a.tagName==="A"){a=a.getAttribute("data-nohref")==="1";break a}a=!1}a&&b.preventDefault()},!0);}).call(this);</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#1967d2}em{font-weight:bold;font-style:normal}.lst{height:25px;width:496px}.gsfi,.lst{font:18px arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}body{background:#fff;color:#000}a{color:#681da8;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#1967d2}a:visited{color:#681da8}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-size:11px}.lsbb{background:#f8f9fa;border:solid 1px;border-color:#dadce0 #70757a #70757a #dadce0;height:30px}.lsbb{display:block}#WqQANb a{display:inline-block;margin:0 12px}.lsb{background:url(/images/nav_logo229.png) 0 -261px repeat-x;color:#000;border:none;cursor:pointer;height:30px;margin:0;outline:0;font:15px arial,sans-serif;vertical-align:top}.lsb:active{background:#dadce0}.lst:focus{outline:none}.Ucigb{width:458px}</style><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){window.google.erd={jsr:1,bv:2060,de:true};
var g=this||self;var k,l=(k=g.mei)!=null?k:1,n,p=(n=g.sdo)!=null?n:!0,q=0,r,t=google.erd,v=t.jsr;google.ml=function(a,b,d,m,e){e=e===void 0?2:e;b&&(r=a&&a.message);d===void 0&&(d={});d.cad="ple_"+google.ple+".aple_"+google.aple;if(google.dl)return google.dl(a,e,d,!0),null;b=d;if(v<0){window.console&&console.error(a,b);if(v===-2)throw a;b=!1}else b=!a||!a.message||a.message==="Error loading script"||q>=l&&!m?!1:!0;if(!b)return null;q++;d=d||{};b=encodeURIComponent;var c="/gen_204?atyp=i&ei="+b(google.kEI);google.kEXPI&&(c+="&jexpid="+b(google.kEXPI));c+="&srcpg="+b(google.sn)+"&jsr="+b(t.jsr)+
"&bver="+b(t.bv);t.dpf&&(c+="&dpf="+b(t.dpf));var f=a.lineNumber;f!==void 0&&(c+="&line="+f);var h=a.fileName;h&&(h.indexOf("-extension:/")>0&&(e=3),c+="&script="+b(h),f&&h===window.location.href&&(f=document.documentElement.outerHTML.split("\n")[f],c+="&cad="+b(f?f.substring(0,300):"No script found.")));google.ple&&google.ple===1&&(e=2);c+="&jsel="+e;for(var u in d)c+="&",c+=b(u),c+="=",c+=b(d[u]);c=c+"&emsg="+b(a.name+": "+a.message);c=c+"&jsst="+b(a.stack||"N/A");c.length>=12288&&(c=c.substr(0,12288));a=c;m||google.log(0,"",a);return a};window.onerror=function(a,b,d,m,e){r!==a&&(a=e instanceof Error?e:Error(a),d===void 0||"lineNumber"in a||(a.lineNumber=d),b===void 0||"fileName"in a||(a.fileName=b),google.ml(a,!1,void 0,!1,a.name==="SyntaxError"||a.message.substring(0,11)==="SyntaxError"||a.message.indexOf("Script error")!==-1?3:0));r=null;p&&q>=l&&(window.onerror=null)};})();</script></head><body bgcolor="#fff"><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){var src='/images/nav_logo229.png';var iesg=false;document.body.onload = function(){window.n && window.n();if (document.images){new Image().src=src;}
if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"><div id=gbar><nobr><b class=gb1>C&#259;utare</b> <a class=gb1 href="https://www.google.com/imghp?hl=ro&tab=wi">Imagini</a> <a class=gb1 href="https://maps.google.ro/maps?hl=ro&tab=wl">Maps</a> <a class=gb1 href="https://play.google.com/?hl=ro&tab=w8">Play</a> <a class=gb1 href="https://www.youtube.com/?tab=w1">YouTube</a> <a class=gb1 href="https://news.google.com/?tab=wn">&#536;tiri</a> <a class=gb1 href="https://mail.google.com/mail/?tab=wm">Gmail</a> <a class=gb1 href="https://drive.google.com/?tab=wo">Drive</a> <a class=gb1 style="text-decoration:none" href="https://www.google.ro/intl/ro/about/products?tab=wh"><u>Mai multe</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a href="http://www.google.ro/history/optout?hl=ro" class=gb4>Istoric Web</a> | <a  href="/preferences?hl=ro" class=gb4>Set&#259;ri</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=ro&passive=true&continue=https://www.google.com/&ec=GAZAAQ" class=gb4>Conecta&#539;i-v&#259;</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div></div><center><br clear="all" id="lgpd"><div id="XjhHGf"><img alt="Google" height="92" src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png" style="padding:28px 0 14px" width="272" id="hplogo"><br><br></div><form action="/search" name="f"><table cellpadding="0" cellspacing="0"><tr valign="top"><td width="25%">&nbsp;</td><td align="center" nowrap=""><input name="ie" value="ISO-8859-1" type="hidden"><input value="ro" name="hl" type="hidden"><input name="source" type="hidden" value="hp"><input name="biw" type="hidden"><input name="bih" type="hidden"><div class="ds" style="height:32px;margin:4px 0"><div style="position:relative;zoom:1"><input class="lst Ucigb" style="margin:0;padding:5px 8px 0 6px;vertical-align:top;color:#000;padding-right:38px" autocomplete="off" value="" title="C&#259;utare Google" maxlength="2048" name="q" size="57"><img src="/textinputassistant/tia.png" style="position:absolute;cursor:pointer;right:5px;top:4px;z-index:300" data-script-url="/textinputassistant/13/ro_tia.js" id="tsuid_1" alt="" height="23" width="27"><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){var id='tsuid_1';document.getElementById(id).onclick = function(){var s = document.createElement('script');s.src = this.getAttribute('data-script-url');document.body.appendChild(s);};})();</script></div></div><br style="line-height:0"><span class="ds"><span class="lsbb"><input class="lsb" value="C&#259;utare Google" name="btnG" type="submit"></span></span><span class="ds"><span class="lsbb"><input class="lsb" id="tsuid_2" value="M&#259; simt norocos" name="btnI" type="submit"><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){var id='tsuid_2';document.getElementById(id).onclick = function(){if (this.form.q.value){this.checked = 1;if (this.form.iflsig)this.form.iflsig.disabled = false;}
else top.location='/doodles/';};})();</script><input value="AL9hbdgAAAAAZrtreKJIVxxSKtiRTo0I9Q6IenTpcBTB" name="iflsig" type="hidden"></span></span></td><td class="fl sblc" align="left" nowrap="" width="25%"><a href="/advanced_search?hl=ro&amp;authuser=0">C&#259;utare avansat&#259;</a></td></tr></table><input id="gbv" name="gbv" type="hidden" value="1"><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){var a,b="1";if(document&&document.getElementById)if(typeof XMLHttpRequest!="undefined")b="2";else if(typeof ActiveXObject!="undefined"){var c,d,e=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(c=0;d=e[c++];)try{new ActiveXObject(d),b="2"}catch(h){}}a=b;if(a=="2"&&location.search.indexOf("&gbv=2")==-1){var f=google.gbvu,g=document.getElementById("gbv");g&&(g.value=a);f&&window.setTimeout(function(){location.href=f},0)};}).call(this);</script></form><div style="font-size:83%;min-height:3.5em"><br><div id="gws-output-pages-elements-homepage_additional_languages__als"><style>#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:#474747;display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}</style><div id="SIvCob">Google oferit în:  <a href="https://www.google.com/setprefs?sig=0_qugwtgFPLAr5dN9MwBi5ODDnxa8%3D&amp;hl=hu&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjCtMOwh_KHAxWvh_0HHaYPCPIQ2ZgBCAY">magyar</a>    <a href="https://www.google.com/setprefs?sig=0_qugwtgFPLAr5dN9MwBi5ODDnxa8%3D&amp;hl=de&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjCtMOwh_KHAxWvh_0HHaYPCPIQ2ZgBCAc">Deutsch</a>    <a href="https://www.google.com/setprefs?sig=0_qugwtgFPLAr5dN9MwBi5ODDnxa8%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjCtMOwh_KHAxWvh_0HHaYPCPIQ2ZgBCAg">English</a>  </div></div></div><span id="footer"><div style="font-size:10pt"><div style="margin:19px auto;text-align:center" id="WqQANb"><a href="/intl/ro/ads/">Publicitate</a><a href="http://www.google.ro/intl/ro/services/">Solu&#355;ii de afaceri</a><a href="/intl/ro/about.html">Totul despre Google</a><a href="https://www.google.com/setprefdomain?prefdom=RO&amp;prev=https://www.google.ro/&amp;sig=K_t1xDZ7VaJAlf_hlY8UrxOqfcqu0%3D">Google.ro</a></div></div><p style="font-size:8pt;color:#70757a">&copy; 2024 - <a href="/intl/ro/policies/privacy/">Confiden&#539;ialitate</a> - <a href="/intl/ro/policies/terms/">Termeni</a></p></span></center><script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){window.google.cdo={height:757,width:1440};(function(){var a=window.innerWidth,b=window.innerHeight;if(!a||!b){var c=window.document,d=c.compatMode=="CSS1Compat"?c.documentElement:c.body;a=d.clientWidth;b=d.clientHeight}
if(a&&b&&(a!=google.cdo.width||b!=google.cdo.height)){var e=google,f=e.log,g="/client_204?&atyp=i&biw="+a+"&bih="+b+"&ei="+google.kEI,h="",k=[],l=window.google!==void 0&&window.google.kOPI!==void 0&&window.google.kOPI!==0?window.google.kOPI:null;l!=null&&k.push(["opi",l.toString()]);for(var m=0;m<k.length;m++){if(m===0||m>0)h+="&";h+=k[m][0]+"="+k[m][1]}f.call(e,"","",g+h)};}).call(this);})();</script>  <script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){google.xjs={basecomb:'/xjs/_/js/k\x3dxjs.hp.en.GeIoccJKIHY.O/ck\x3dxjs.hp.JZzp5p4LDgc.L.X.O/am\x3dAQAAAAEAAAAAAAAAAAAAAAAAAAAAQAQAAAAAAAAAgAEABwAAIAAgIAAAAAAAPAAAAAgAAAiAEAAAA4AAAMCB-I4AQAAsAgDACw/d\x3d1/ed\x3d1/dg\x3d0/ujg\x3d1/rs\x3dACT90oEb4ThEVHnNMKee-bSRV0SJ79mwqA',basecss:'/xjs/_/ss/k\x3dxjs.hp.JZzp5p4LDgc.L.X.O/am\x3dAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAIAAgIAAAAAAAAAAAAAgAAAiAEAAAA4A/rs\x3dACT90oGUyTkymmKwrJB19tzveO0qpWZ-EQ',basejs:'/xjs/_/js/k\x3dxjs.hp.en.GeIoccJKIHY.O/am\x3dAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAgAEABwAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAMCB-I4AQAAsAgDACw/dg\x3d0/rs\x3dACT90oEr6pAzKKU4-RomjOkmg_dHONYHDg',excm:[]};})();</script>  <link href="/xjs/_/ss/k=xjs.hp.JZzp5p4LDgc.L.X.O/am=AQAAAAEAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAIAAgIAAAAAAAAAAAAAgAAAiAEAAAA4A/d=1/ed=1/rs=ACT90oGUyTkymmKwrJB19tzveO0qpWZ-EQ/m=sb_he,d" rel="stylesheet" nonce="3RPf7BDhHalNhbebg0g8WQ">      <script nonce="3RPf7BDhHalNhbebg0g8WQ">(function(){var u='/xjs/_/js/k\x3dxjs.hp.en.GeIoccJKIHY.O/am\x3dAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAgAEABwAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAMCB-I4AQAAsAgDACw/d\x3d1/ed\x3d1/dg\x3d3/rs\x3dACT90oEr6pAzKKU4-RomjOkmg_dHONYHDg/m\x3dsb_he,d';var st=1;var amd=1000;var mmd=0;var pod=true;
var f=this||self,g=function(a){return a};var h;var k=function(a){this.g=a};k.prototype.toString=function(){return this.g+""};var l=function(a){return a instanceof k&&a.constructor===k?a.g:"type_error:TrustedResourceUrl"},m={};
var n=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;var p="alternate author bookmark canonical cite help icon license modulepreload next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" ");function q(a,b){a.src=l(b);var c,d;(c=(b=(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)==null?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};var r=function(a){var b=document;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};function t(a){a=a===null?"null":a===void 0?"undefined":a;if(h===void 0){var b=null;var c=f.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:g,createScript:g,createScriptURL:g})}catch(d){f.console&&f.console.error(d.message)}h=b}else h=b}a=(b=h)?b.createScriptURL(a):a;return new k(a,m)};google.ps===void 0&&(google.ps=[]);function w(){var a=u,b=function(){};google.lx=google.stvsc?b:function(){x(a);google.lx=b};google.bx||google.lx()}function y(a,b){b&&q(a,t(b));var c=a.onload;a.onload=function(d){c&&c(d);google.ps=google.ps.filter(function(e){return a!==e})};google.ps.push(a);document.body.appendChild(a)}google.as=y;function x(a){google.timers&&google.timers.load&&google.tick&&google.tick("load","xjsls");var b=r("SCRIPT");b.onerror=function(){google.ple=1};b.onload=function(){google.ple=0};google.xjsus=void 0;y(b,a);google.aple=-1;google.dp=!0}
function z(){var a=[u];if(!google.dp){for(var b=0;b<a.length;b++){var c=r("LINK"),d=c,e=t(a[b]);if(e instanceof k)d.href=l(e).toString(),d.rel="preload";else{if(p.indexOf("preload")===-1)throw Error("a`preload");e=n.test(e)?e:void 0;e!==void 0&&(d.href=e,d.rel="preload")}c.setAttribute("as","script");document.body.appendChild(c)}google.dp=!0}};function A(a){var b=a.getAttribute("jscontroller");return(b==="UBXHI"||b==="R3fhkb"||b==="TSZEqd")&&a.hasAttribute("data-src")}function B(){for(var a=document.getElementsByTagName("img"),b=0,c=a.length;b<c;b++){var d=a[b];if(d.hasAttribute("data-lzy_")&&Number(d.getAttribute("data-atf"))&1&&!A(d))return!0}return!1}for(var C=document.getElementsByTagName("img"),D=0,E=C.length;D<E;++D){var F=C[D];Number(F.getAttribute("data-atf"))&1&&A(F)&&(F.src=F.getAttribute("data-src"))};var G,H,I,J,K;function L(){google.xjsu=u;f._F_jsUrl=u;J=function(){w()};G=!1;H=(st===1||st===3)&&!!google.caft&&!B();I=(st===2||st===3)&&!!google.rairicb&&!B();K=pod}function M(){G||H||I||(J(),G=!0)}setTimeout(function(){google&&google.tick&&google.timers&&google.timers.load&&google.tick("load","xjspls");L();if(H||I){if(H){var a=function(){H=!1;M()};google.caft(a);window.setTimeout(a,amd)}I&&(a=function(){I=!1;M()},(0,google.rairicb)(a),window.setTimeout(a,mmd));K&&(G||z())}else J()},0);})();window._ = window._ || {};window._DumpException = _._DumpException = function(e){throw e;};window._s = window._s || {};_s._DumpException = _._DumpException;window._qs = window._qs || {};_qs._DumpException = _._DumpException;(function(){var t=[1,4,0,0,0,287309824,0,5309440,117473680,8389136,131584,294912,60,536870944,67584,2629824,948027392,16777787,8898,752];window._F_toggles = window._xjs_toggles = t;})();window._F_installCss = window._F_installCss || function(css){};(function(){google.jl={bfl:0,dw:false,ine:false,ubm:false,uwp:true,vs:false};})();(function(){var pmc='{\x22d\x22:{},\x22sb_he\x22:{\x22agen\x22:false,\x22cgen\x22:false,\x22client\x22:\x22heirloom-hp\x22,\x22dh\x22:true,\x22ds\x22:\x22\x22,\x22fl\x22:true,\x22host\x22:\x22google.com\x22,\x22jsonp\x22:true,\x22msgs\x22:{\x22cibl\x22:\x22\\u0218terge c\\u0103utarea\x22,\x22dym\x22:\x22Ai dorit s\\u0103 scrii:\x22,\x22lcky\x22:\x22M\\u0103 simt norocos\x22,\x22lml\x22:\x22Afl\\u0103 mai multe\x22,\x22psrc\x22:\x22Aceast\\u0103 c\\u0103utare a fost eliminat\\u0103 din \\u003Ca href\x3d\\\x22/history\\\x22\\u003EIstoricul dvs. Web\\u003C/a\\u003E\x22,\x22psrl\x22:\x22Elimin\\u0103\x22,\x22sbit\x22:\x22Caut\\u0103 dup\\u0103 imagine\x22,\x22srch\x22:\x22C\\u0103utare Google\x22},\x22ovr\x22:{},\x22pq\x22:\x22\x22,\x22rfs\x22:[],\x22stok\x22:\x22TBuldBXUDBkVy7KqQly5Cs-c_Qs\x22}}';google.pmc=JSON.parse(pmc);})();(function(){var b=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};
var e=this||self;var g,h;a:{for(var k=["CLOSURE_FLAGS"],l=e,n=0;n<k.length;n++)if(l=l[k[n]],l==null){h=null;break a}h=l}var p=h&&h[610401301];g=p!=null?p:!1;var q,r=e.navigator;q=r?r.userAgentData||null:null;function t(a){return g?q?q.brands.some(function(c){return(c=c.brand)&&c.indexOf(a)!=-1}):!1:!1}function u(a){var c;a:{if(c=e.navigator)if(c=c.userAgent)break a;c=""}return c.indexOf(a)!=-1};function v(){return g?!!q&&q.brands.length>0:!1}function w(){return u("Safari")&&!(x()||(v()?0:u("Coast"))||(v()?0:u("Opera"))||(v()?0:u("Edge"))||(v()?t("Microsoft Edge"):u("Edg/"))||(v()?t("Opera"):u("OPR"))||u("Firefox")||u("FxiOS")||u("Silk")||u("Android"))}function x(){return v()?t("Chromium"):(u("Chrome")||u("CriOS"))&&!(v()?0:u("Edge"))||u("Silk")}function y(){return u("Android")&&!(x()||u("Firefox")||u("FxiOS")||(v()?0:u("Opera"))||u("Silk"))};var z=v()?!1:u("Trident")||u("MSIE");y();x();w();var A=!z&&!w(),D=function(a){if(/-[a-z]/.test("ved"))return null;if(A&&a.dataset){if(y()&&!("ved"in a.dataset))return null;a=a.dataset.ved;return a===void 0?null:a}return a.getAttribute("data-"+"ved".replace(/([A-Z])/g,"-$1").toLowerCase())};var E=[],F=null;function G(a){a=a.target;var c=performance.now(),f=[],H=f.concat,d=E;if(!(d instanceof Array)){var m=typeof Symbol!="undefined"&&Symbol.iterator&&d[Symbol.iterator];if(m)d=m.call(d);else if(typeof d.length=="number")d={next:b(d)};else throw Error("b`"+String(d));for(var B=[];!(m=d.next()).done;)B.push(m.value);d=B}E=H.call(f,d,[c]);if(a&&a instanceof HTMLElement)if(a===F){if(c=E.length>=4)c=(E[E.length-1]-E[E.length-4])/1E3<5;if(c){c=google.getEI(a);a.hasAttribute("data-ved")?f=a?D(a)||"":"":f=(f=
a.closest("[data-ved]"))?D(f)||"":"";f=f||"";if(a.hasAttribute("jsname"))a=a.getAttribute("jsname");else{var C;a=(C=a.closest("[jsname]"))==null?void 0:C.getAttribute("jsname")}google.log("rcm","&ei="+c+"&tgtved="+f+"&jsname="+(a||""))}}else F=a,E=[c]}window.document.addEventListener("DOMContentLoaded",function(){document.body.addEventListener("click",G)});}).call(this);</script></body></html>

**Comment by adrianvintu** [comment]
Response as zip via notepad++

[response.zip](https://github.com/user-attachments/files/16600201/response.zip)
